name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_URL: ${{ secrets.API_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch API data and generate static HTML
        run: |
          echo "Fetching data from API with key $API_KEY"
          DATA=$(curl -s "${API_URL}?key=${API_KEY}&q=example")

          mkdir -p public
          echo "<!DOCTYPE html><html><head><title>API Data</title></head><body><pre>" > public/index.html
          echo "$DATA" >> public/index.html
          echo "</pre></body></html>" >> public/index.html

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./public
