name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test API connectivity (GET)
        run: |
          echo "Testing API connectivity with GET..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -H "API-KEY: $API_KEY" "https://api.loopy5418.dev/yt-search?query=example")
          STATUS=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          echo "API response status: $STATUS"
          echo "API response body: $BODY"
          if [ "$STATUS" -ne 200 ]; then
            echo "API GET request failed with status $STATUS"
          fi

      - name: Test API connectivity (POST)
        run: |
          echo "Testing API connectivity with POST..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST -H "API-KEY: $API_KEY" -H "Content-Type: application/json" --data '{"query":"example"}' "https://api.loopy5418.dev/yt-search")
          STATUS=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          echo "API response status: $STATUS"
          echo "API response body: $BODY"
          if [ "$STATUS" -ne 200 ]; then
            echo "API POST request failed with status $STATUS"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy
        uses: actions/deploy-pages@v4
